### PR TITLE
argument missed , updated regex

### PR DESCRIPTION
**Pull request by dipcore**
just a small fix

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
@dipcore Cool! I wasn't sure if anyone other than myself would ever use this stuff!

What are you working on? I might have some stuff laying around that's of interest to you. I haven't touched it in months, but my TV is presently running AOSP (poorly) and thinks it's a mobile phone when you turn it on 😉

**Comment by dipcore** [comment]
Just bought a new TV http://www.lemall.com/us/product/x355.html 
It's also based on MSTAR, but different version of CPU MSD6A928 
So now I'm trying to unpack my .bin file. The header script is basically the same: http://pastebin.com/GhUNw5kK

Ideally I would like to install AOSP too, but I do not have kernel sources for my platform and I think will never get it, but at least I could play with system.img

it would be much appreciated if you could share any info with me.

**Comment by Benjamin-Dobell** [comment]
@dipcore Hopefully the TV is similar enough to mine (I have two, with similar MStar chipsets) and some of this applies.

# Factory Menu

Once the TV boots in Android, open the TV app/widget. On your remote control enter:
- Menu
- 2
- 0
- 0
- 8

Lots of cool features in here.

# UART / Shell / TTY

_I highly recommend this before flashing anything._

If your TV is similar to mine, you can probably get a serial TTY prompt (UART) through the VGA port.

Pins 5-8 - Ground
Pin 12 = TX
Pin 15 = RX

Buy a FT232 USB to UART adapter (e.g.https://www.sparkfun.com/products/12731 or https://www.adafruit.com/product/2264) and VGA connector you can cut up. You can buy VGA headers but I find it easier to buy a cable and use a multimeter to establish which pin is connected to which wire (once I've cut the cable in half).

With UART you can watch the entire boot log, access UBoot (bootloader) menu and access Android's shell.

# MStar Upgrade
1. Turn the TV off at the wall (or the power switch on the TV - not standby on the remote).
2. Turn the TV power back on.
3. Press the power/standby button on the remote (to turn the TV on).
4. **Hold** "Volume Down" on the remote.

You can also get into here from the factory menu (assuming your TV boots). But this procedure will work even if the TV won't boot up.

# Android Recovery

Same as above, but instead of "Volume Down" hold "Program/Channel Down".

# RE: Kernel

Your chipset is presumably newer than the one here, so you may not have a lot of luck. However, it seems MStar try build fairly generic kernels that will work on a number of devices. I know that firmware for one TV can be flashed onto a similar chipset TV and will _mostly_ work. Mind you, given your chipset is **newer**, I'm not sure that logic will hold up.

Regardless, definitely get UART working before you try flash anything. Having output and a command line interface will make your life _so_ much easier.

...

Being a different TV your mileage may vary. I'm curious, so please let me know which of the above is applicable.

**Comment by Benjamin-Dobell** [comment]
Oh, to get the TTY working during boot there's a button you can push on the remote - "Volume Up" maybe? If not you can enable it from the "Factory Menu" _or_ in the firmware flashing script (bundled into MStarUpgrade.bin) by adding:

```
setenv UARTOnOff on
```

before:

```
saveenv
```

**Comment by Benjamin-Dobell** [comment]
Just remembered one more thing, I never finished updating the README to properly explain how to use the tools. `build_mstar_upgrade.rb` takes a "firmware_info" file, which is just a quick format I threw together. A valid file looks like this:

```
##### PARTITIONS #####

misc 00080000
recovery 00A00000 KALED473DSMTZA-MstarUpgrade.part.recovery
boot 00400000 boot.uboot
system 019000000 system.ext4
userdata A2800000 userdata.ext4.lzo lzo
cache 12C00000 KALED473DSMTZA-MstarUpgrade.part.cache lzo
tvservice 05000000 KALED473DSMTZA-MstarUpgrade.part.tvservice
tvcustomer 01000000 KALED473DSMTZA-MstarUpgrade.part.tvcustomer
tvdatabase 00800000 KALED473DSMTZA-MstarUpgrade.part.tvdatabase
customercfg 03000000 KALED473DSMTZA-MstarUpgrade.part.customercfg

##### ENV #####

MIU0_GROUP_SELMIU = "8000:0060:1420:0FC0"
MIU1_GROUP_SELMIU = "4E08:0100:0201:0000"
MIU0_GROUP_PRIORITY = "1:0:3:2"
MIU1_GROUP_PRIORITY = "1:0:2:3"
MS_MEM = "LX_MEM=0x12400000 EMAC_MEM=0x100000 DRAM_LEN=0x20000000 LX_MEM2=0x0A0000000,0xC300000"
KERNEL_PROTECT = "DRAM_SIZE1=0x20000000 DRAM_SIZE2=0x10000000"
ROOT = "root=/dev/ram rw rootwait"
bootargs = "console=ttyS0,115200 androidboot.console=ttyS0 $(ROOT) init=/init $(MS_MEM) CORE_DUMP_PATH=/data/core_dump.%%p.gz KDebug=0 str_crc=1"
upgrade_mode = "0"
db_table = "0"
UARTOnOff = “on”
factory_burnin_mode = "0"
bootdelay = "1"
verify = "n"
bootcmd = "mmc read.p 0x45000000 boot 0x400000\; bootm 0x45000000"
```

**Comment by dipcore** [comment]
Did you try to build MStarUpgrade.bin to upgrade just a single partition?

**Comment by Benjamin-Dobell** [comment]
No, mind you I'm sure you could. Given I had all the partitions I guess I just never saw the point. I have flashed plenty of times though. Certainly messed up the builds from time to time, but this procedure doesn't touch the bootloaders, so you can always get back into upgrade mode and return to stock.

**Comment by dipcore** [comment]
Can you explain me in the build script what is this for

```
file.seek 0
poor_mans_consistency_check = file.read 16

file.seek end_pos
file.write poor_mans_consistency_check
```

?

**Comment by Benjamin-Dobell** [comment]
@dipcore It's just copying the first 16 bytes of the file to the last 16 bytes. I've done this simply because it matches the official firmware files I downloaded.

I can't remember whether this was actually necessary though. The source code for the flashing utility (`MBoot/KkApp/src`) is included in this repo; feel free to take a look and find out.

**Comment by dipcore** [comment]
@Benjamin-Dobell Honestly my Ruby skills are not that good, so I had to write a small python script to unpack my .bin My system.img is split on chunks and each chunk is lzo-packed. Also i have 3 different versions of userdata.img Unfortunately boot.img and recovery.img are encrypted :( 
All my header script: http://pastebin.com/cF53BLUJ

So what I have:

```
-rwxrwxrwx 1 root root       75776 Sep 10 19:37 boot1.img
-rwxrwxrwx 1 root root     4069296 Sep 10 19:33 boot.img
-rwxrwxrwx 1 root root         544 Sep 10 19:33 bootSign
-rwxrwxrwx 1 root root    16957440 Nov 20  2015 cache.img
-rwxrwxrwx 1 root root    16957440 Nov 20  2015 fastplay.img
-rwxrwxrwx 1 root root     1515008 Sep 10 19:37 MBOOT.img
-rwxrwxrwx 1 root root        1904 Sep 10 19:33 NuttxConfig
-rwxrwxrwx 1 root root     6179504 Sep 10 19:33 recovery.img
-rwxrwxrwx 1 root root         544 Sep 10 19:33 recoverySign
-rwxrwxrwx 1 root root       65536 Sep 10 19:37 RTPM.img
-rwxrwxrwx 1 root root   524980224 Sep 10 19:33 system.img
-rwxrwxrwx 1 root root         544 Sep 10 19:33 teeSign
-rwxrwxrwx 1 root root    33554432 Sep 10 19:33 tvconfig.img
-rwxrwxrwx 1 root root    16777216 Sep 10 19:33 tvcustomer.img
-rwxrwxrwx 1 root root     8388608 Sep 10 19:33 tvdatabase.img
-rwxrwxrwx 1 root root    62914560 Sep 10 19:33 tvservice.img
-rwxrwxrwx 1 root root 12885061632 Nov 20  2015 userdata1.img
-rwxrwxrwx 1 root root    59719680 Nov 20  2015 userdata2.img
-rwxrwxrwx 1 root root  4295151616 Nov 20  2015 userdata.img
```

In the upgrade.bin I have three different BOOTs,

BOOT#1 boot.img (3.87 MB) is encrypted (As I see, it should contain android kernel and initramfs). 
bootSign file contains some kind of encryption signature:

```
mmc erase.p boot
filepartload 20400000 LetvUpgrade.bin 5ea000 3e17b0
mmc write.p 20400000 boot 3e17b0 1

filepartload 20400000 LetvUpgrade.bin 9cc000 220
store_secure_info bootSign 20400000
```

BOOT#2 SBOOT (74KB)

```
filepartload 20400000 LetvUpgrade.bin 24175000 12800
mmc write.boot 1 20400000 0 12800
```

And the last one is MBOOT:

```
filepartload 20400000 LetvUpgrade.bin 24188000 171e00
mmc write.p 20400000 MBOOT 171e00
```

Why do they put all that to the upgrade.bin? :( So it seems like in any case I'll have to build some custom upgrade.bin, without boots

**Comment by Benjamin-Dobell** [comment]
Yeah, my split script only unpacks the individual flashed partitions. It doesn't try decompress (LZO) them or pull apart the boot image (uboot multi image), I just used existing tools for all that.

Is there somewhere I can download firmware for your TV? I'll take a look at it when I've got a chance.

**Comment by dipcore** [comment]
https://drive.google.com/drive/folders/0B9s5NUf528GlYVBMMzlYc3JxTjg

**Comment by dipcore** [comment]
Here is my python scripts https://github.com/dipcore/mstar-bin-tool

**Comment by dipcore** [comment]
Hm, interesting script: https://github.com/Benjamin-Dobell/kogan-tv-gpl/blob/master/MBoot/sboot/util/build_MbootUpgrade_image.sh

There are functions:

```
function func_post_process(){
    echo "% <- this is end of file symbol" >> $SCRIPT_FILE
    func_pad_script; # padding to $SCRIPT_SIZE(0x4000), and Mboot.bin align 4byte.
    cat $SCRIPT_FILE >> $OUTPUT_IMG
    cat $INPUT_IMG >> $OUTPUT_IMG
    func_set_crc_to_image;
    func_copy_first_16byte;
    cp $OUTPUT_IMG ../out/
}
```

and

```
function func_set_crc_to_image(){
    #Set Only-Script CRC1
    $CRC $SCRIPT_FILE | xxd -r -p >> $OUTPUT_IMG
    #Set Full-Bin CRC2
    $CRC $OUTPUT_IMG | xxd -r -p >> $OUTPUT_IMG
}
```

So I have to align the bin, add two CRCs (header and merged aligned bin) and first 16 bytes of header script to the end.

Basically that script gives me exact logic of how to build it! :)

**Comment by dipcore** [comment]
Hey,
did you have a chance to look at it?

**Pull request merged**
